# Generated by Django 5.2.1 on 2025-12-24 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('seat_number', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_passengers', to='trips.tripbus')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='trips.trip')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['trip', 'name'], name='passengers__trip_id_97f13e_idx')],
            },
        ),
    ]
