# Generated by Django 5.2.1 on 2026-01-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
