# Generated by Django 5.2.1 on 2026-01-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_alter_passenger_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat_number',
        ),
    ]
