# Generated by Django 5.2.1 on 2026-01-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_passengerbusassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passengerbusassignment',
            new_name='passengers__trip_id_993d30_idx',
            old_name='passengerb_trip_tr_4d7a0f_idx',
        ),
    ]
