# Generated by Django 5.2.1 on 2026-01-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0006_relax_assignment_one_to_one'),
        ('passengers', '0006_rename_passengerb_trip_tr_4d7a0f_idx_passengers__trip_id_993d30_idx'),
    ]

    operations = [
    ]
