# Generated by ChatGPT on 2026-01-22
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Passenger = apps.get_model("passengers", "Passenger")
    PassengerTransfer = apps.get_model("passengers", "PassengerTransfer")

    # Populate passenger.tenant using the existing trip relation
    for passenger in Passenger.objects.select_related("trip"):
        trip = getattr(passenger, "trip", None)
        if trip and trip.tenant_id and not passenger.tenant_id:
            passenger.tenant_id = trip.tenant_id
            passenger.save(update_fields=["tenant"])

    # Populate transfer.trip using the passenger's current trip
    for transfer in PassengerTransfer.objects.select_related("passenger"):
        passenger = getattr(transfer, "passenger", None)
        trip = getattr(passenger, "trip", None)
        if trip and not transfer.trip_id:
            transfer.trip_id = trip.id
            transfer.save(update_fields=["trip"])


def backwards(apps, schema_editor):
    # No-op rollback; data loss would occur when reintroducing passenger.trip
    return


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0007_merge_20260122_0844"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="passengertransfer",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger_transfers",
                to="trips.trip",
            ),
        ),
        migrations.AlterField(
            model_name="passengertransfer",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="passengers.passenger",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="passenger",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to="accounts.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="passengertransfer",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger_transfers",
                to="trips.trip",
            ),
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="trip",
        ),
        migrations.AlterUniqueTogether(
            name="passengertransfer",
            unique_together={("passenger", "trip")},
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(
                fields=["tenant", "name"], name="passenger_tenant_name_idx"
            ),
        ),
    ]
