# Generated by Django 5.2.1 on 2026-04-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('passengers', '0008_passenger_tenant_and_transfer_trip'),
        ('trips', '0002_add_driver_to_tripbus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedBus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trip', 'sequence'],
            },
        ),
        migrations.RemoveIndex(
            model_name='passenger',
            name='passengers__trip_id_97f13e_idx',
        ),
        migrations.RenameIndex(
            model_name='passenger',
            new_name='passengers__tenant__3d77b4_idx',
            old_name='passenger_tenant_name_idx',
        ),
        migrations.AlterUniqueTogether(
            name='passengertransfer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='passengerbusassignment',
            name='trip_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_assignments', to='trips.tripbus'),
        ),
        migrations.AddConstraint(
            model_name='passengertransfer',
            constraint=models.UniqueConstraint(fields=('passenger', 'trip'), name='unique_passenger_transfer_per_trip'),
        ),
        migrations.AddField(
            model_name='importedbus',
            name='mapped_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_buses', to='fleet.bus'),
        ),
        migrations.AddField(
            model_name='importedbus',
            name='mapped_trip_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_bus_sources', to='trips.tripbus'),
        ),
        migrations.AddField(
            model_name='importedbus',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_buses', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='passengerbusassignment',
            name='imported_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_assignments', to='passengers.importedbus'),
        ),
        migrations.AlterUniqueTogether(
            name='importedbus',
            unique_together={('trip', 'sheet_name')},
        ),
    ]
