# Generated by Django 5.2.1 on 2026-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0009_importedbus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='extra_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
