# Generated by Django 5.2.1 on 2026-06-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0010_passenger_extra_info'),
        ('trips', '0002_add_driver_to_tripbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerbusassignment',
            name='trip_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_assignments', to='trips.tripbus'),
        ),
    ]
