# Generated by Django 5.2.1 on 2026-01-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(help_text='Order of this round within the trip')),
                ('estimate_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('doing', 'Doing'), ('done', 'Done')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='trips.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
                'unique_together': {('trip', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='RoundBus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_buses', to='rounds.round')),
                ('trip_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_buses', to='trips.tripbus')),
            ],
            options={
                'ordering': ['round', 'trip_bus'],
                'unique_together': {('round', 'trip_bus')},
            },
        ),
    ]
