# Generated by Django 5.2.1 on 2026-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_add_finalized_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='estimate_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
