# Generated by Django 5.2.1 on 2026-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0003_alter_round_estimate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundbus',
            name='checkout_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
