# Generated by Django 5.2.1 on 2026-06-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_roundbus_checkout_finalized_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundbus',
            name='snapshot_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
