# Generated by Django 5.2.1 on 2026-06-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0005_roundbus_snapshot_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='actual_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='estimate_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
