# Generated by Django 5.2.1 on 2026-06-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0006_round_round_date_alter_round_actual_time_and_more'),
        ('trips', '0003_alter_tripbus_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['trip', 'round_date', 'sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('trip', 'round_date', 'sequence')},
        ),
    ]
