# Generated by Django 5.2.1 on 2025-12-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Nullable for superusers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.tenant'),
        ),
    ]
