# Generated by Django 5.2.1 on 2025-12-24 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True),
        ),
    ]
