# Generated by Django 5.2.1 on 2026-06-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_phone_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
