# Generated by Django 5.2.1 on 2026-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_company_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_device_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_in_app_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
