# Generated by Django 5.2.1 on 2026-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_receive_device_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_device_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
