# Generated by Django 5.2.1 on 2025-12-24 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='passengers.passenger')),
                ('round_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rounds.roundbus')),
            ],
            options={
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['passenger', 'round_bus'], name='transaction_passeng_88b6b8_idx')],
            },
        ),
    ]
