"""
Django settings for tour_management project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

# import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

env_path = Path(__file__).resolve().parent.parent / ".env"
if env_path.exists():
    env.read_env(env_path)

# Kiểm tra
# print("DEBUG - Loading .env from:", env_path)
# print("DEBUG - DATABASE_URL =", env("DATABASE_URL", default="KHÔNG TÌM THẤY"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dummy")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

LOCAL_APPS = [
    "accounts",
    "fleet",
    "trips",
    "passengers",
    "rounds",
    "transactions",
    "core",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "drf_spectacular",
    "corsheaders",  # Added for CORS support
    "rest_framework_simplejwt",
]

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "tour_management.middleware.DisableCSRFMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tour_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "react" / "builded"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tour_management.wsgi.application"

# CORS configuration
MIDDLEWARE = ["corsheaders.middleware.CorsMiddleware"] + MIDDLEWARE

# Lấy CORS origins từ ALLOWED_HOSTS trong .env
allowed_hosts = os.getenv("ALLOWED_HOSTS", "localhost").split(",")
allowed_ports = os.getenv("ALLOWED_PORTS", "3000").split(",")
CORS_ALLOWED_ORIGINS = []
for host in allowed_hosts:
    if host != "*":  # Bỏ qua wildcard
        for port in allowed_ports:
            CORS_ALLOWED_ORIGINS.append(f"http://{host}:{port}")
            CORS_ALLOWED_ORIGINS.append(f"https://{host}:{port}")

# Fallback nếu không có hosts hợp lệ
if not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "https://localhost:3000"]

CORS_ALLOW_CREDENTIALS = True

# CSRF settings
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "https://tour-management.local",
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv("DJANGO_DEBUG", "False") == "True":
    db = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "default_db"),
        "USER": os.getenv("DB_USER", "default_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "default_pass"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
else:
    db = env.db()

DATABASES = {
    "default": db,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

redis_host = os.getenv("REDIS_HOST", "localhost")
redis_port = os.getenv("REDIS_PORT", "6379")
redis_db = os.getenv("REDIS_DB", "1")
redis_password = os.getenv("REDIS_PASSWORD", "")

if redis_password:
    default_redis_location = (
        f"redis://:{redis_password}@{redis_host}:{redis_port}/{redis_db}"
    )
else:
    default_redis_location = f"redis://{redis_host}:{redis_port}/{redis_db}"

redis_location = os.getenv("REDIS_URL", default_redis_location)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": redis_location,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    # Extra lookup directories for collectstatic to find static files
)

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"

# ASGI application entrypoint
ASGI_APPLICATION = "tour_management.asgi.application"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {"format": "%(levelname)s %(asctime)s %(message)s"},
        "verbose": {
            "format": "%(asctime)s - %(filename)s:%(lineno)d - %(name)s - %(levelname)s - %(message)s"
        },
        "vietnam_time": {
            "()": "tour_management.formatters.VietnamTimeFormatter",
            "format": "%(asctime)s - %(filename)s:%(lineno)d - %(name)s - %(levelname)s - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "system": {
            "level": "DEBUG",  # Cho phép tất cả levels
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "vietnam_time",
            "filename": os.path.join(BASE_DIR, "logs/system.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
        },
        "console": {
            "level": "DEBUG",  # Cho phép tất cả levels
            "class": "logging.StreamHandler",
            "formatter": "vietnam_time",
        },
        "application": {
            "level": "DEBUG",  # Cho phép tất cả levels
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "vietnam_time",
            "filename": os.path.join(BASE_DIR, "logs/application.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
        },
        "general": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "vietnam_time",
            "filename": os.path.join(BASE_DIR, "logs/general.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
        },
    },
    "root": {
        "handlers": ["system"],  # Chỉ system log cho Django framework
        "level": "WARNING",  # Chỉ WARNING và ERROR cho system
    },
    "loggers": {
        "django": {
            "handlers": ["general"],  # Django logs vào general.log
            "level": "WARNING",  # Chỉ hiện WARNING và ERROR của Django
            "propagate": False,
        },
        "core": {
            "handlers": ["application"],  # Chỉ application.log
            "level": "DEBUG",
            "propagate": False,  # Không propagate
        },
        "utils": {
            "handlers": ["application"],  # Chỉ application.log
            "level": "DEBUG",
            "propagate": False,  # Không propagate
        },
        "common": {
            "handlers": ["application"],  # Chỉ application.log
            "level": "DEBUG",
            "propagate": False,  # Không propagate
        },
        "tour_management": {
            "handlers": ["application"],  # Chỉ application.log
            "level": "DEBUG",
            "propagate": False,  # Không propagate
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    # Pagination style
    "DEFAULT_PAGINATION_CLASS": "common.pagination.CustomPagination",
    "PAGE_SIZE": 10,
    # Other settings
    "DATE_INPUT_FORMATS": ["%Y-%m-%d"],
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("ACCESS_TOKEN_MINUTES", "5"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("REFRESH_TOKEN_DAYS", "1"))),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Tour Management API",
    "DESCRIPTION": "API documentation for Tour Management",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "tagsSorter": "alpha",
    },
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]",
}

# Email Configuration
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", default="587"))
EMAIL_USE_TLS = bool(os.getenv("EMAIL_USE_TLS", default="True"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", default="noreply@tour-management.local"
)
