export const ROUTES = {
  DASHBOARD: "/",
  LOGIN: "/view/login",
  REGISTER: "/view/register",
  FORGOT_PASSWORD: "/view/forgot-password",
  RESET_PASSWORD: "/view/reset-password",
  TRIP: "/view/trip",
  ROUND: "/view/round",
  BUS: "/view/bus",
  PASSENGER: "/view/passenger",
  ACCOUNT: "/view/account",
  TENANT: "/view/tenant",
  TRANSACTIONS: "/view/transactions",
  PROFILE: "/view/profile",
  GUIDE: "/view/guide",
  NOTIFICATIONS: "/view/notifications",
  SETTINGS: "/view/settings",
  NOT_FOUND: "*",
};
